# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCannotcommentNoreaction():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cannotcommentNoreaction(self):
    self.driver.get("https://postemote.pythonanywhere.com/")
    self.driver.set_window_size(943, 1400)
    self.driver.find_element(By.ID, "comment8191fe56-13a4-44c4-92ca-9fbd86725096").click()
    self.driver.find_element(By.ID, "comment8191fe56-13a4-44c4-92ca-9fbd86725096").send_keys("cannot comment")
    self.driver.find_element(By.ID, "comment8191fe56-13a4-44c4-92ca-9fbd86725096").send_keys(Keys.ENTER)
  
