# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSurprisedreact():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_surprisedreact(self):
    self.driver.get("https://postemote.pythonanywhere.com/surprising_sort")
    self.driver.set_window_size(943, 1400)
    self.driver.find_element(By.CSS_SELECTOR, ".suprised-button8191fe56-13a4-44c4-92ca-9fbd86725096").click()
  
