# Generated by Django 4.1.7 on 2023-03-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_comment_user_remove_post_user_comment_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default='46510', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(default='CECB4', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.CharField(default='B0BF0', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
