# Generated by Django 4.1.7 on 2023-03-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_comment_comment_id_alter_post_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default='3668D1A3FD', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(default='FB1BCBFE92', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.CharField(default='7E170C50C5', max_length=50, primary_key=True, serialize=False),
        ),
    ]
