# Generated by Django 4.1.7 on 2023-03-11 05:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_profile_id_user_profile_u_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='angry_likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='happy_likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sad_likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shocked_likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_likes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
