# Generated by Django 4.1.7 on 2023-03-12 22:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_profile_angry_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuprisedReact',
            fields=[
                ('superised_react_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
