# Generated by Django 4.1.7 on 2023-03-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_comment_angry_reaction_comment_happy_reaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='angry_reaction',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='happy_reaction',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='sad_reaction',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='surprised_reaction',
        ),
        migrations.AddField(
            model_name='comment',
            name='reaction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
